name: Checkmarx ONE Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: test_naftali
          cx_client_id: GithubHarsh
          cx_client_secret: UdRVsCscEJFd7UuomFWFXTWA8t9xb6aJ
